name: Contar Arquivos à Meia-Noite
on:
  schedule:
    - cron: "0 0 * * *"  # 00:00 UTC
  workflow_dispatch:

jobs:
  nightly_count:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Contar arquivos (exclui .git)
        run: |
          TOTAL=$(find . -type f ! -path "./.git/*" | wc -l)
          echo "Total de arquivos: $TOTAL"
